### PR TITLE
Update the packaging and exception message

### PR DESCRIPTION
**Pull request by samassot**
Hi,
I made a little update for 2 needs : 
- be able to open sources from eclipse on project using the library from maven projects: updated pom with source plugin
- See the drl compilation errors in the junits output : updated the injector exception message with the errors.

regards
Samuel.

### CODE REVIEW

**Comment by maciejwalkowiak** [comment]
Thanks again! Great idea with adding sources and Javadocs to JAR file. I like also the idea of adding Drools error messages to exception message. 

I don't think it's a good idea to print error messages in unit tests - it messes up the test output, and we don't really need it since we test everything using assertions.

**Comment by samassot** [comment]
I agree with you for the error logging.
I did not removed anything on this point.

I added (on my unit test framework) some rules listeners to be able to
assert on rule fireing and event movements.
I could send you some code sample if you are interested.

2014-06-13 13:23 GMT+02:00 Maciej Walkowiak notifications@github.com:

**Comment by maciejwalkowiak** [comment]
Sure, let's see. If you find it useful for your Drools project probably others will find it useful as well.

**Comment by samassot** [comment]
Ok I'll package you that as soon as possible.

2014-06-13 16:59 GMT+02:00 Maciej Walkowiak notifications@github.com:

**Comment by samassot** [comment]
Hi !
Please find in the attachment some code snippet of the tools I developped
to get more readable assertions in the unit tests.

See if you think it's usefull.

regards.
Samuel.

2014-06-13 17:43 GMT+02:00 Samuel-Alexandre Massot samassot@gmail.com:

**Comment by maciejwalkowiak** [comment]
It's not possible to attach files to github comments. Maybe you can create repo with your code?

**Comment by maciejwalkowiak** [comment]
Unfortunately due to the lack of time I am not able to continue developing and maintaining `junit-drools` project. Thank you for your contributions and I hope you will find one of the forks still maintained and helpful for you!

**Pull request closed without merging**
